config/routes.rb
Rails.application.routes.draw do
  get 'tasks/index'

  get 'tasks/new'

  get 'tasks/show'

  get 'tasks/edit'

  get 'tasks/update'

  get 'tasks/destroy'

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get "/auth/:provider/callback" => "sessions#create_from_omniauth"

  resources :users

  resources :users do
    resources :tasks
  end

  resources :posts, only: [:create, :destroy]

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :user
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = current_user.tasks
  end

  def new
    @task = current_user.tasks.build
  end

  def create
    @task = current_user.tasks.create(task_params)
    
    respond_to do |format|
      format.html {redirect_to user_tasks_path}
      format.js
    end

    # if @task.save
    #   flash[:success] = "Task Created!"
    #   redirect_to user_tasks_path
    # else
    #   render 'new'
    # end
  end

  def show
    @tasks = current_user.tasks
  end

  def edit
  end

  def update
    @task = Task.find(params[:id])
    @task.update_attributes(status: params[:task][:status])
    # params[:task][:status]

    post_content = "#{current_user.name} has just completed a task: #{@task.title}"
    @post = current_user.posts.build(content: post_content)
        if @post.save
          flash[:success] = "Task Updated and Post created!"
          redirect_to user_tasks_path
        else
          render 'static_pages/home'
        end
  end

  def destroy
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :complete_by)
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_for [current_user, @task], :remote => true do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>

<%= f.label :description %>
<%= f.text_field :description %>

<%= f.label :complete_by %>
<%= f.date_field :complete_by, class: 'form-control'%>

<%= f.submit "Add task", class: "btn btn-primary" %>
<% end %>

app/views/tasks/_task.html.erb
<div class="row">
  <div class="col-md-8">
<li id="task-<%= task.id %>">

<span class="user"><%= link_to task.user.name, task.user %></span>
  <span class="content"><%= task.title %></span>
  <span class="timestamp">
    Due on <%= task.complete_by %>.
  </span>
</li>
</div>

  <% if !task.status %>
  <div class="col-md-2">
    <%= form_for [current_user, task] do |f| %>
    <%= f.check_box :status %>
    </div>
    <div class="col-md-2">
    <%= f.submit "Update" %>
    </div>
    <%end%>
  <%else%>
    <div class="col-md-2"></div>
    <div class="col-md-2">
      <h3><span class="label label-default">Completed</span></h3>
    </div>
    <%end%>

</div>

app/views/tasks/create.js.erb
console.log("create.js.erb file");
$('#new_task').remove();
$('#new_link').show();
$('.tasks').append('<%= j render(@task) %>');

app/views/tasks/edit.html.erb
<h1>Tasks#edit</h1>
<p>Find me in app/views/tasks/edit.html.erb</p>

app/views/tasks/index.html.erb
<div class="center jumbotron">
  <h1>Ready to create a task?</h1>

  <%= link_to "Create Now!", new_user_task_path, class: "btn btn-lg btn-primary", id: "new_link", remote: true %>

</div>

<% if @tasks.any? %>
<h3>Task</h3>
<ol class="tasks">
 <%= render @tasks %>
</ol>
<% end %>

app/views/tasks/new.html.erb
<% provide(:title, 'Add new task') %>
<h1>New Task</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for([current_user, @task]) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :description %>
      <%= f.text_field :description %>

      <%= f.label :complete_by %>
      <%= f.date_field :complete_by, class: 'form-control'%>

      <%= f.submit "Add task", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/tasks/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>